version: '3.5'

services:
  people_api:
    container_name: people_api
    image: postgres
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  app:
    build: .
    depends_on:
      - people_api
    ports:
      - "8083:8083"
    environment:
      - POSTGRES_HOST=people_api
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=people_api
volumes:
  postgres: